services:
  # Frontend Service (Next.js)
  - type: web
    name: finmark-frontend
    env: node
    buildCommand: cd finmark-ecommerce && npm install && npm run build
    startCommand: cd finmark-ecommerce && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: finmark-db
          property: connectionString

  # Backend Service (User Service)
  - type: web
    name: finmark-backend
    env: node
    buildCommand: cd user-service && npm install
    startCommand: cd user-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: finmark-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://finmark-frontend.onrender.com

# Database
databases:
  - name: finmark-db
    databaseName: finmark
    user: finmark_user